### PR TITLE
Add Tests for AlgoliaPLaces (first draft)

### PR DESCRIPTION
**Pull request by sheub**
Hi @Fabex,

I took the time to implements the tests of the Algolia provider in geocoder-php. These tests should pass the travisCI build but are still in a first draft:

- I did not test the provider with real API_KEY and APP_ID
- I got sometimes during the tests a `degradedQuery` results, for which:

> If the query doesn't retrieve any results, we fallback on a degraded query strategy: all words are considered optional and we only target cities

Those results won't get any `postcode` and `city`. So the `buildResult` will return an error. We should check for `degradedQuery` server response before or during the call of `buildResult`
I have just added `degradedQuery` as comment in this function.

### CODE REVIEW

**Comment by Fabex** [comment]
Hi @sheub 
thank your for your PR request.
But this repository is dead. In fact I create a PR directly on Geocoder repository

https://github.com/geocoder-php/Geocoder/pull/854

So I will try to retrieve your commits and add them to the Geocoder PR

**Comment by sheub** [comment]
Hi Fabex,
Thanks for your answer and Sorry for the last commits... I didn't saw that there were already done. So you can simply ignore them.

**Comment by Fabex** [comment]
@sheub in fact can you rewrite your tests from my other PR it will be more simple to add them, please.

**Comment by sheub** [comment]
@Fabex , ok, so I will close this PR. I have checkout the Branch algolia-places-provider locally and started to add the test to it.
 The best will be if you invite me as collaborator to fabex/Geocoder/ so that I can commit directly to it.

**Pull request closed without merging**
